/**
 * Tests for lib/specify-revise.mjs — Task 7 of review-block-auto-retry.plan.md.
 *
 * Covers:
 *   - Revision N → N+1 bump + `updated:` set to today
 *   - Frontmatter fields not implicated byte-identical
 *   - Body sections whose anchor is NOT in any blocker entry byte-identical
 *   - `spec_revised` event emitted with correct payload
 *   - `.blockers.md` cleared when all blockers addressed
 *   - `.review.md` NOT cleared
 *   - Missing sidecars → NO_REVIEW_SIDECARS
 *   - Non-blocked status + auto mode → SPEC_NOT_BLOCKED
 *   - Path-traversal rejected (SEC-1)
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';

import { reviseSpec } from '../../lib/specify-revise.mjs';
import { readEvents } from '../../lib/lifecycle-state.mjs';

function makeBlockedSpec({ revision = 1, status = 'review-blocked' } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'adev-revise-'));
  mkdirSync(join(root, '.context-index/specs/cross-cutting'), { recursive: true });
  mkdirSync(join(root, '.context-index/lifecycle-state'), { recursive: true });
  writeFileSync(join(root, '.context-index', 'manifest.yaml'),
    'project:\n  name: test\nlifecycle:\n  event_diagnostics: off\n');
  const specPath = '.context-index/specs/cross-cutting/sample.spec.md';
  const specBody = [
    '# Live Spec: Sample',
    '',
    '---',
    `revision: ${revision}`,
    'created: 2026-05-01',
    'updated: 2026-05-01',
    `status: ${status}`,
    'risk_level: low',
    '---',
    '',
    '## Behavioral Contract',
    '',
    'The sample feature does sample things.',
    '',
    '## Behaviors',
    '',
    '1. **When** invoked **then** does X.',
    '',
    '## Acceptance Criteria',
    '',
    '- [ ] X works',
    ''
  ].join('\n');
  writeFileSync(join(root, specPath), specBody);
  return { root, specPath };
}

function writeReviewSidecar(root, specPath) {
  const reviewPath = specPath.replace(/\.spec\.md$/, '.review.md');
  writeFileSync(join(root, reviewPath),
    '# Architecture Review: sample\n\n> Verdict: BLOCK\n\nFindings:\n- SA-1: missing precondition\n');
  return reviewPath;
}

function writeBlockersSidecar(root, specPath, findings) {
  const blockersPath = specPath.replace(/\.spec\.md$/, '.blockers.md');
  const lines = [
    '<!-- Generated by lib/blockers-writer.mjs -->',
    `# Blockers: ${specPath}`,
    '',
    '> Spec revision: 1',
    '> Entries: ' + findings.length,
    '',
  ];
  for (const f of findings) {
    lines.push(`## ${f.blocker_id}`);
    lines.push('');
    lines.push('```yaml');
    lines.push(`blocker_id: ${f.blocker_id}`);
    lines.push(`section_anchor: ${f.section_anchor}`);
    lines.push('```');
    lines.push('');
    lines.push('```');
    lines.push(f.prose);
    lines.push('```');
    lines.push('');
  }
  writeFileSync(join(root, blockersPath), lines.join('\n'));
  return blockersPath;
}

test('reviseSpec bumps revision N → N+1 and sets updated to today', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 3 });
  try {
    writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:missing-precondition:aaaaaaaa', section_anchor: 'preconditions', prose: 'block 1' },
    ]);
    const result = reviseSpec({ specPath, projectRoot: root });
    assert.equal(result.fromRevision, 3);
    assert.equal(result.toRevision, 4);
    const body = readFileSync(join(root, specPath), 'utf8');
    assert.ok(body.includes('revision: 4'));
    const today = new Date().toISOString().slice(0, 10);
    assert.ok(body.includes(`updated: ${today}`), `expected updated: ${today}`);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec preserves unimplicated frontmatter fields byte-identically', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1 });
  try {
    writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:x:11111111', section_anchor: 'preconditions', prose: 'b' },
    ]);
    reviseSpec({ specPath, projectRoot: root });
    const body = readFileSync(join(root, specPath), 'utf8');
    // Unimplicated frontmatter fields preserved
    assert.ok(body.includes('created: 2026-05-01'));
    assert.ok(body.includes('risk_level: low'));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec preserves spec body sections not implicated by blockers (byte-identical)', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1 });
  try {
    writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:x:11111111', section_anchor: 'preconditions', prose: 'b' },
    ]);
    const originalBody = readFileSync(join(root, specPath), 'utf8');
    reviseSpec({ specPath, projectRoot: root });
    const newBody = readFileSync(join(root, specPath), 'utf8');
    // Body sections (Behaviors, Acceptance Criteria) preserved
    assert.ok(newBody.includes('## Behaviors'));
    assert.ok(newBody.includes('1. **When** invoked **then** does X.'));
    assert.ok(newBody.includes('- [ ] X works'));
    // The implicated section "preconditions" (which doesn't actually exist as a
    // heading in this fixture) is treated as a hint — the writer doesn't
    // remove anything; the operator (or a follow-up revise) addresses it.
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec emits a spec_revised event with correct payload', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1 });
  try {
    writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:x:11111111', section_anchor: 'preconditions', prose: 'b1' },
      { blocker_id: 'sec:y:22222222', section_anchor: 'errors', prose: 'b2' },
    ]);
    reviseSpec({ specPath, projectRoot: root });
    const events = readEvents(root, specPath);
    const revised = events.filter(e => e.event === 'spec_revised');
    assert.equal(revised.length, 1);
    const ev = revised[0];
    assert.equal(ev.from_revision, 1);
    assert.equal(ev.to_revision, 2);
    assert.ok(Array.isArray(ev.addressed_blocker_ids));
    assert.ok(Array.isArray(ev.unresolved_blocker_ids));
    // All blockers from the input are flagged as addressed by default
    // (the patch addresses them by acknowledgement; a later review will
    // verify resolution).
    assert.deepEqual(ev.addressed_blocker_ids.sort(), ['sa:x:11111111', 'sec:y:22222222']);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec clears .blockers.md when revision succeeds (all blockers marked addressed)', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1 });
  try {
    writeReviewSidecar(root, specPath);
    const blockersPath = writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:x:11111111', section_anchor: 'preconditions', prose: 'b' },
    ]);
    reviseSpec({ specPath, projectRoot: root });
    // .blockers.md should be cleared
    assert.ok(!existsSync(join(root, blockersPath))
      || readFileSync(join(root, blockersPath), 'utf8').length === 0,
      '.blockers.md should be cleared (deleted or emptied) after successful revise');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec does NOT clear .review.md (next review rewrites it)', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1 });
  try {
    const reviewPath = writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:x:11111111', section_anchor: 'preconditions', prose: 'b' },
    ]);
    reviseSpec({ specPath, projectRoot: root });
    assert.ok(existsSync(join(root, reviewPath)), '.review.md must be preserved');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec rejects when .review.md or .blockers.md is missing — NO_REVIEW_SIDECARS', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1 });
  try {
    // No sidecars
    assert.throws(
      () => reviseSpec({ specPath, projectRoot: root }),
      (e) => e.code === 'NO_REVIEW_SIDECARS',
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec rejects auto-mode on non-blocked spec — SPEC_NOT_BLOCKED', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1, status: 'review-passed' });
  try {
    writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:x:11111111', section_anchor: 'preconditions', prose: 'b' },
    ]);
    assert.throws(
      () => reviseSpec({ specPath, projectRoot: root, autoMode: true }),
      (e) => e.code === 'SPEC_NOT_BLOCKED',
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec transitions spec status review-blocked → review-pending', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1 });
  try {
    writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:x:11111111', section_anchor: 'preconditions', prose: 'b' },
    ]);
    reviseSpec({ specPath, projectRoot: root });
    const body = readFileSync(join(root, specPath), 'utf8');
    assert.ok(body.includes('status: review-pending'));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec rejects path-traversal — INVALID_SPEC_PATH (SEC-1)', () => {
  const { root, specPath } = makeBlockedSpec({ revision: 1 });
  try {
    assert.throws(
      () => reviseSpec({ specPath: '../../etc/passwd', projectRoot: root }),
      (e) => e.code === 'INVALID_SPEC_PATH',
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// ── adev-plugin-akoy.1 regression ─────────────────────────────────────────
//
// 129 of this repo's 254 .spec.md files open with an H1 + MULTI-LINE HTML
// comment before the fence. The frontmatter reader used to break on the
// comment's continuation lines (non-blank, no leading `#`, no leading `<!--`),
// so it never found the fence and returned `{}` — reviseSpec then read no
// `revision:` at all. The fixtures above only cover an H1 + blank line, which
// is why this went unnoticed.
//
// This also guards `rewriteFrontmatter`'s splice: it rebuilds the file as
// lines[0..openIdx] + newFrontmatter + lines[closeIdx..], so a wrong openIdx
// silently corrupts or drops the preamble rather than erroring.

function makeBlockedSpecWithCommentPreamble({ revision = 1 } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'adev-revise-preamble-'));
  mkdirSync(join(root, '.context-index/specs/cross-cutting'), { recursive: true });
  mkdirSync(join(root, '.context-index/lifecycle-state'), { recursive: true });
  writeFileSync(join(root, '.context-index', 'manifest.yaml'),
    'project:\n  name: test\nlifecycle:\n  event_diagnostics: off\n');
  const specPath = '.context-index/specs/cross-cutting/sample.spec.md';
  const preamble = [
    '# Live Spec: Sample',
    '',
    '<!-- REVISION HISTORY',
    '     - rev 1: initial draft. This continuation line is what broke the old',
    '       reader: non-blank, no leading hash, no leading comment-open.',
    '-->',
  ];
  const specBody = [
    ...preamble,
    '---',
    `revision: ${revision}`,
    'created: 2026-05-01',
    'updated: 2026-05-01',
    'status: review-blocked',
    'risk_level: low',
    '---',
    '',
    '## Behavioral Contract',
    '',
    'The sample feature does sample things.',
    '',
    '## Acceptance Criteria',
    '',
    '- [ ] X works',
    '',
  ].join('\n');
  writeFileSync(join(root, specPath), specBody);
  return { root, specPath, preamble };
}

test('reviseSpec reads revision from behind a multi-line comment preamble (akoy.1)', () => {
  const { root, specPath } = makeBlockedSpecWithCommentPreamble({ revision: 3 });
  try {
    writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:missing-precondition:aaaaaaaa', section_anchor: 'preconditions', prose: 'block 1' },
    ]);
    const result = reviseSpec({ specPath, projectRoot: root });
    assert.equal(result.fromRevision, 3, 'must read revision 3 from behind the comment');
    assert.equal(result.toRevision, 4);
    assert.ok(readFileSync(join(root, specPath), 'utf8').includes('revision: 4'));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('reviseSpec preserves an H1 + multi-line comment preamble byte-identically (akoy.1)', () => {
  const { root, specPath, preamble } = makeBlockedSpecWithCommentPreamble({ revision: 1 });
  try {
    writeReviewSidecar(root, specPath);
    writeBlockersSidecar(root, specPath, [
      { blocker_id: 'sa:missing-precondition:aaaaaaaa', section_anchor: 'preconditions', prose: 'block 1' },
    ]);
    reviseSpec({ specPath, projectRoot: root });
    const rewritten = readFileSync(join(root, specPath), 'utf8');
    assert.equal(
      rewritten.split('\n').slice(0, preamble.length).join('\n'),
      preamble.join('\n'),
      'the preamble must survive the frontmatter rewrite unchanged',
    );
    // And the fence must still sit immediately after it — exactly once.
    assert.equal(rewritten.split('\n')[preamble.length], '---');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
