// lib/gitignore-paths.mjs
//
// Canonical source of truth for the `adev:gitignore` managed block.
//
// MANAGED_GITIGNORE_PATHS is an ordered, frozen list of `{ path, comment? }`
// tuples consumed by:
//   - lib/gitignore-installer.mjs (renderBlock / ensureManagedBlock)
//   - tests/lib/gitignore-paths-dogfood.test.mjs (parity check against this
//     repo's own `.gitignore`)
//
// SEC-4 (non-sensitivity): entries are user-visible — they ship in committed
// `.gitignore` files. Keep them non-sensitive: no credentials, no PII, no
// host-specific paths. The list represents *categories* of ephemeral state
// that adev-managed projects must not commit; it never carries operator data.
//
// SEC-3 (load-time invariants): the IIFE below asserts at module-load time
// that no entry carries a newline / null byte or a literal marker token
// (which would otherwise break the paired-marker contract of
// lib/gitignore-installer.mjs).

const GITIGNORE_OPEN_MARKER = "# >>> adev:gitignore >>>";
const GITIGNORE_CLOSE_MARKER = "# <<< adev:gitignore <<<";

/**
 * Ordered list of paths managed by the `adev:gitignore` paired-marker block.
 *
 * Order is significant: the installer emits paths in this exact sequence,
 * and the dogfood parity test (`tests/lib/gitignore-paths-dogfood.test.mjs`)
 * does a byte-equality check on the resulting block.
 *
 * @type {ReadonlyArray<{ path: string, comment?: string }>}
 */
export const MANAGED_GITIGNORE_PATHS = Object.freeze([
  { path: ".context-index/hygiene/", comment: "hygiene reports (regenerated)" },
  { path: ".context-index/packets/", comment: "review packets (regenerated)" },
  { path: ".context-index/.token-cursor.json", comment: "session-tracking cursor" },
  { path: ".context-index/.reminder-counter", comment: "issue-reminder counter" },
  { path: ".context-index/.session-tracking.jsonl", comment: "session telemetry" },
  { path: ".context-index/user-config", comment: "local user config override" },
  { path: ".context-index/.context-preflight-ok", comment: "preflight session flag" },
  { path: ".context-index/.execution-state.json", comment: "execution state (transient)" },
  { path: ".context-index/.advisory-counter", comment: "lifecycle-gate advisory counter" },
  {
    path: ".context-index/lifecycle-state/*.json",
    // SA-1 absorption — comment names the load-bearing rationale (jsonl
    // event logs ARE committed; only the *.json build-state files are ignored).
    comment:
      "build-state JSON (jsonl event logs ARE committed; only *.json build-state ignored) — SA-1",
  },
  {
    path: ".context-index/build-state/*.json",
    comment: "legacy build-state (pre-rename)",
  },
  { path: ".context-index/tasks/tasks.json.lock", comment: "issue-board CAS lock" },
  {
    path: ".context-index/tasks/tasks.json.*.tmp",
    comment: "issue-board atomic-write temp",
  },
  {
    path: ".context-index/tasks/.migrate-state.json",
    comment: "backend-migration resume state",
  },
  {
    path: ".beads/",
    comment: "beads board — linked git worktree against beads-board, not main's tree",
  },
  {
    path: ".context-index/tasks/.board-migrate-state.json",
    comment: "board-migrate resume checkpoint",
  },
  {
    path: "*.partial",
    // SA-5 / CON-4: cross-cutting handoff from
    // .context-index/specs/cross-cutting/incremental-artifact-writes.spec.md
    comment:
      "incremental artifact write — satisfies cross-cutting/incremental-artifact-writes:236",
  },
  { path: "*.partial.lock", comment: "incremental artifact lock" },
  {
    path: ".gitignore.*.tmp",
    // SEC-2: the installer writes <gitignore>.<pid>.tmp + atomic rename;
    // ignore the temp pattern so a half-finished tmp does not leak into git.
    comment: "gitignore-installer atomic-write temp (SEC-2)",
  },
  { path: ".adev/", comment: "prototype workspace" },
  {
    path: ".githooks/*.adev",
    // Chained-hook mode moves each real hook body to <name>.adev and replaces
    // the tracked .githooks/<name> with a wrapper that calls it. The .adev
    // bodies are regenerated by `adev install`/`adev upgrade` from the
    // plugin's own hooks/, so committing them would ship a stale copy that
    // silently diverges from the installed plugin version.
    comment: "chained-hook bodies (regenerated by adev install; wrapper is committed, these are not)",
  },
]);

// ─── SEC-3 load-time invariants ─────────────────────────────────────────────
(function assertInvariants() {
  for (const entry of MANAGED_GITIGNORE_PATHS) {
    if (typeof entry !== "object" || entry === null) {
      throw new Error("MANAGED_GITIGNORE_PATHS: each entry must be an object");
    }
    if (typeof entry.path !== "string" || entry.path.length === 0) {
      throw new Error(
        `MANAGED_GITIGNORE_PATHS: entry.path must be a non-empty string (got ${JSON.stringify(entry)})`,
      );
    }
    if (entry.comment !== undefined && typeof entry.comment !== "string") {
      throw new Error(
        `MANAGED_GITIGNORE_PATHS: entry.comment must be a string when present (got ${JSON.stringify(entry)})`,
      );
    }
    if (/[\n\r\0]/.test(entry.path)) {
      throw new Error(
        `MANAGED_GITIGNORE_PATHS: entry.path has forbidden newline/null byte: ${JSON.stringify(entry.path)}`,
      );
    }
    if (entry.comment !== undefined && /[\n\r\0]/.test(entry.comment)) {
      throw new Error(
        `MANAGED_GITIGNORE_PATHS: entry.comment has forbidden newline/null byte: ${JSON.stringify(entry.comment)}`,
      );
    }
    if (
      entry.path.includes(GITIGNORE_OPEN_MARKER) ||
      entry.path.includes(GITIGNORE_CLOSE_MARKER)
    ) {
      throw new Error(
        `MANAGED_GITIGNORE_PATHS: entry.path must not contain marker tokens: ${JSON.stringify(entry.path)}`,
      );
    }
    if (
      entry.comment !== undefined &&
      (entry.comment.includes(GITIGNORE_OPEN_MARKER) ||
        entry.comment.includes(GITIGNORE_CLOSE_MARKER))
    ) {
      throw new Error(
        `MANAGED_GITIGNORE_PATHS: entry.comment must not contain marker tokens: ${JSON.stringify(entry.comment)}`,
      );
    }
  }
})();

export default MANAGED_GITIGNORE_PATHS;
