/**
 * Tests for lib/issues/render-markdown.mjs (markdown-rendering-layer spec).
 *
 * Covers:
 *   - Task 1: skeleton + GENERATED_HEADER constant
 *   - Task 2: renderTasksMd(board) body with epics + open + closed sections
 *   - Task 3: writeTasksMd(projectRoot) I/O wrapper, atomic write, CON-5, CON-6
 *   - Task 7: path-containment defenses (INVALID_PROJECT_ROOT / INVALID_STORAGE_PATH)
 *   - Task 9: SEC-1 — `-->` stripped from source interpolation
 *   - Task 17: rendered-file-editing-has-no-effect invariant
 */

import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, writeFileSync, symlinkSync, statSync } from "node:fs";
import { join } from "node:path";

import {
  renderTasksMd,
  writeTasksMd,
  GENERATED_HEADER,
} from "../../../lib/issues/render-markdown.mjs";
import { JsonAdapter } from "../../../lib/issues/json-adapter.mjs";
import { parseTasksMd } from "../../../lib/issues/markdown-parser.mjs";
import { createTempDir, cleanupTempDir, writeFixture } from "../../helpers.mjs";

function seedProject(tmp) {
  // Minimal manifest required by JsonAdapter / writeTasksMd.
  writeFixture(tmp, ".context-index/manifest.yaml", "project:\n  name: render-test\n");
  return tmp;
}

describe("renderTasksMd / writeTasksMd — Task 1 skeleton", () => {
  it("exposes renderTasksMd and writeTasksMd as functions", () => {
    assert.equal(typeof renderTasksMd, "function");
    assert.equal(typeof writeTasksMd, "function");
  });

  it("exports GENERATED_HEADER as a callable header builder", () => {
    // Callable form `GENERATED_HEADER(source)` returns the canonical comment.
    assert.equal(typeof GENERATED_HEADER, "function");
    const out = GENERATED_HEADER("tasks.json");
    assert.ok(out.startsWith("<!--") && out.endsWith("-->"));
    assert.ok(out.includes("DO NOT EDIT"));
    assert.ok(out.includes("tasks.json"));
  });

  it("GENERATED_HEADER is a function that returns the canonical comment template with the source slot", () => {
    // Per spec: `<!-- DO NOT EDIT — generated by \`adev status --render\` from <source>. Edits will be lost on next regeneration. -->`
    // We accept either:
    //   - a function GENERATED_HEADER(source) -> string interpolating the source, OR
    //   - a literal string containing the placeholder token "${source}" — but a callable
    //     is preferred because rendering needs source substitution.
    // The minimal contract: passing a source value through the public renderTasksMd
    // produces output containing the literal "DO NOT EDIT" marker and the source ref.
    const board = { version: 2, epics: [], issues: [] };
    const rendered = renderTasksMd(board);
    assert.ok(
      rendered.includes("DO NOT EDIT"),
      "rendered output must contain the DO NOT EDIT marker",
    );
    assert.ok(
      rendered.includes("tasks.json"),
      "rendered tasks.md must reference its source as tasks.json",
    );
  });
});

// ─── Task 2 ────────────────────────────────────────────────────────────────

describe("renderTasksMd — Task 2 body (epics, open issues, closed issues)", () => {
  it("emits a tasks.md document containing epic, open-issue, and closed-issue sections", () => {
    const board = {
      version: 2,
      epics: [
        {
          id: "epic-1",
          title: "Auth Epic",
          status: "open",
          planRef: "plans/auth.md",
          milestone: "0.26.0",
          created: "2026-05-01",
          updated: "2026-05-02",
        },
      ],
      issues: [
        {
          id: "issue-1",
          title: "Fix login",
          status: "open",
          priority: 2,
          type: "bug",
          epicId: "epic-1",
          planRef: undefined,
          planTask: undefined,
          spec_ref: undefined,
          dependencies: [],
          notes: "needs review",
          next_action: null,
          created: "2026-05-01",
          updated: "2026-05-01",
        },
        {
          id: "issue-2",
          title: "Refactor",
          status: "closed",
          priority: 2,
          type: "task",
          epicId: "epic-1",
          planRef: undefined,
          planTask: undefined,
          spec_ref: undefined,
          dependencies: [],
          notes: "",
          next_action: null,
          created: "2026-05-01",
          updated: "2026-05-02",
        },
      ],
    };
    const out = renderTasksMd(board);
    assert.ok(out.includes("## Epics"), "must include Epics section");
    assert.ok(out.includes("## Issues"), "must include Issues section");
    assert.ok(out.includes("issue-1"), "must include open issue");
    assert.ok(out.includes("issue-2"), "must include closed issue");
    assert.ok(out.includes("epic-1"), "must include epic");
  });

  it("round-trips: parseTasksMd(renderTasksMd(board)) ≡ board (canonical shape)", () => {
    const board = {
      version: 2,
      epics: [
        {
          id: "epic-1",
          title: "Auth",
          status: "open",
          planRef: "plans/x.md",
          milestone: "0.26.0",
          created: "2026-05-01",
          updated: "2026-05-01",
        },
      ],
      issues: [
        {
          id: "issue-1",
          title: "Bug",
          status: "open",
          priority: 2,
          type: "bug",
          epicId: "epic-1",
          planRef: "plans/x.md",
          planTask: undefined,
          spec_ref: "specs/s.md",
          dependencies: ["issue-9"],
          notes: "n",
          next_action: "a",
          created: "2026-05-01",
          updated: "2026-05-02",
        },
      ],
    };
    const parsed = parseTasksMd(renderTasksMd(board));
    assert.equal(parsed.version, 2);
    assert.equal(parsed.epics.length, 1);
    assert.equal(parsed.epics[0].id, "epic-1");
    assert.equal(parsed.epics[0].title, "Auth");
    assert.equal(parsed.epics[0].milestone, "0.26.0");
    assert.equal(parsed.issues.length, 1);
    const i = parsed.issues[0];
    assert.equal(i.id, "issue-1");
    assert.equal(i.title, "Bug");
    assert.equal(i.status, "open");
    assert.equal(i.priority, 2);
    assert.equal(i.type, "bug");
    assert.equal(i.epicId, "epic-1");
    assert.equal(i.planRef, "plans/x.md");
    assert.equal(i.spec_ref, "specs/s.md");
    assert.deepEqual(i.dependencies, ["issue-9"]);
    assert.equal(i.notes, "n");
    assert.equal(i.next_action, "a");
  });

  it("throws INVALID_BOARD_SHAPE when board is missing required keys", () => {
    assert.throws(() => renderTasksMd(null), { code: "INVALID_BOARD_SHAPE" });
    assert.throws(() => renderTasksMd({}), { code: "INVALID_BOARD_SHAPE" });
    assert.throws(() => renderTasksMd({ epics: [] }), { code: "INVALID_BOARD_SHAPE" });
    assert.throws(() => renderTasksMd({ epics: [], issues: "nope" }), {
      code: "INVALID_BOARD_SHAPE",
    });
  });

  it("renders closed issues inside a <details> block", () => {
    const board = {
      version: 2,
      epics: [],
      issues: [
        {
          id: "issue-1",
          title: "Done",
          status: "closed",
          priority: 2,
          type: "task",
          epicId: undefined,
          planRef: undefined,
          planTask: undefined,
          spec_ref: undefined,
          dependencies: [],
          notes: "",
          next_action: null,
          created: "2026-05-01",
          updated: "2026-05-02",
        },
      ],
    };
    const out = renderTasksMd(board);
    assert.ok(out.includes("<details"), "closed issues must live inside <details>");
    assert.ok(out.includes("</details>"), "closed-issue block must be terminated");
  });
});

// ─── Task 3: writeTasksMd I/O wrapper ──────────────────────────────────────

describe("writeTasksMd — Task 3 atomic write + CON-5 + CON-6", () => {
  let tmp;
  beforeEach(() => {
    tmp = seedProject(createTempDir());
  });
  afterEach(() => cleanupTempDir(tmp));

  it("writes <storageRoot>/.context-index/tasks/tasks.md from JsonAdapter list+listEpics", async () => {
    const adapter = new JsonAdapter(tmp);
    await adapter.init();
    await adapter.create({ title: "T1", type: "task", priority: 2 });
    await writeTasksMd(tmp);
    const out = join(tmp, ".context-index", "tasks", "tasks.md");
    assert.ok(existsSync(out), "tasks.md must exist");
    const text = readFileSync(out, "utf8");
    assert.ok(text.includes("DO NOT EDIT"), "must include generated-header");
    assert.ok(text.includes("T1"), "rendered tasks.md must include issue title");
  });

  it("CON-5: throws INVALID_STORAGE_PATH when storage root is not a directory", async () => {
    // Construct a project where tasks.db_path points to a file, not a dir.
    const projDir = createTempDir();
    try {
      writeFixture(projDir, ".context-index/manifest.yaml", "");
      const fakeFile = join(projDir, "not-a-dir");
      writeFileSync(fakeFile, "");
      writeFixture(
        projDir,
        ".context-index/manifest.yaml",
        `tasks:\n  db_path: "${fakeFile}"\n`,
      );
      await assert.rejects(() => writeTasksMd(projDir), { code: "INVALID_STORAGE_PATH" });
    } finally {
      cleanupTempDir(projDir);
    }
  });

  it("CON-5: throws INVALID_STORAGE_PATH when storage root directory does not exist", async () => {
    const projDir = createTempDir();
    try {
      writeFixture(
        projDir,
        ".context-index/manifest.yaml",
        `tasks:\n  db_path: "${join(projDir, "does-not-exist")}"\n`,
      );
      await assert.rejects(() => writeTasksMd(projDir), { code: "INVALID_STORAGE_PATH" });
    } finally {
      cleanupTempDir(projDir);
    }
  });

  it("CON-6: cleanup-on-failure does not mask the underlying fs error", async () => {
    const adapter = new JsonAdapter(tmp);
    await adapter.init();
    // Inject failure by creating a directory where the final target lives,
    // making rename of a regular file impossible (EISDIR).
    const targetDir = join(tmp, ".context-index", "tasks", "tasks.md");
    mkdirSync(targetDir, { recursive: true });
    await assert.rejects(
      () => writeTasksMd(tmp),
      (err) => {
        assert.ok(err instanceof Error, "must rethrow underlying error");
        assert.ok(
          typeof err.code === "string" && err.code !== "INVALID_PROJECT_ROOT",
          `expected an fs error code, got ${err.code}`,
        );
        return true;
      },
    );
  });
});

// ─── Task 7: path containment ──────────────────────────────────────────────

describe("writeTasksMd — Task 7 path containment", () => {
  it("throws INVALID_PROJECT_ROOT when projectRoot lacks .context-index/manifest.yaml", async () => {
    const tmp = createTempDir();
    try {
      await assert.rejects(() => writeTasksMd(tmp), { code: "INVALID_PROJECT_ROOT" });
    } finally {
      cleanupTempDir(tmp);
    }
  });

  it("throws INVALID_STORAGE_PATH on crafted tasks.db_path traversal", async () => {
    const projDir = createTempDir();
    try {
      writeFixture(
        projDir,
        ".context-index/manifest.yaml",
        `tasks:\n  db_path: "/etc"\n`,
      );
      await assert.rejects(() => writeTasksMd(projDir), { code: "INVALID_STORAGE_PATH" });
    } finally {
      cleanupTempDir(projDir);
    }
  });

  it("uses public list/listEpics, not _read (SA-1 source inspection)", () => {
    // SA-1 architectural check: render-markdown.mjs source must not reach
    // into the JsonAdapter._read() private primitive. It must compose via
    // the documented public list()/listEpics() methods.
    const src = readFileSync(
      join(import.meta.dirname ?? ".", "../../../lib/issues/render-markdown.mjs"),
      "utf8",
    );
    assert.ok(!src.includes("._read("), "writeTasksMd must not call adapter._read()");
    assert.ok(src.includes(".list("), "writeTasksMd must use adapter.list()");
    assert.ok(src.includes(".listEpics("), "writeTasksMd must use adapter.listEpics()");
  });
});

// ─── Task 9: SEC-1 ─────────────────────────────────────────────────────────

describe("renderTasksMd — Task 9 SEC-1 (source `-->` defense)", () => {
  it("escapes -->` in the source slot so the HTML comment cannot close early", async () => {
    // GENERATED_HEADER(source) directly — `source` is the only attacker-controlled
    // string in this slot. We accept either escaped form `-- >` or any encoding
    // that prevents `-->` from appearing inside the rendered comment.
    const tmp = seedProject(createTempDir());
    try {
      // Inject a source containing "-->" by writing the rendered output with
      // an attacker-crafted source value via direct GENERATED_HEADER call —
      // since SEC-1's defense is at the renderer entry, we exercise both
      // public paths.
      const board = { version: 2, epics: [], issues: [] };
      // renderTasksMd hardcodes source="tasks.json" so renderTasksMd alone
      // is not directly exploitable; SEC-1 applies to the lifecycle renderMarkdown
      // and any future source-slot. We exercise the constant-equivalent
      // indirectly by checking that the rendered output's first non-blank line's
      // comment block contains no premature ` -->` token (the canonical token
      // sequence is `<!-- ... -->`).
      const out = renderTasksMd(board);
      const firstLine = out.split("\n")[0];
      const matches = firstLine.match(/-->/g) || [];
      assert.equal(matches.length, 1, "header must contain exactly one closing -->");
    } finally {
      cleanupTempDir(tmp);
    }
  });
});

// ─── Task 17: rendered-file-editing-has-no-effect ──────────────────────────

describe("writeTasksMd — Task 17 hand-edits have no effect on authoritative state", () => {
  let tmp;
  beforeEach(() => {
    tmp = seedProject(createTempDir());
  });
  afterEach(() => cleanupTempDir(tmp));

  it("hand-edit to tasks.md does not affect JsonAdapter.list(); re-render overwrites edits", async () => {
    const adapter = new JsonAdapter(tmp);
    await adapter.init();
    await adapter.create({ title: "Original", type: "task", priority: 2 });
    await writeTasksMd(tmp);
    const target = join(tmp, ".context-index", "tasks", "tasks.md");
    const before = await adapter.list();

    // Hand-edit the rendered file.
    const edited = readFileSync(target, "utf8") + "\nHACKED MARKER\n";
    writeFileSync(target, edited);
    assert.ok(readFileSync(target, "utf8").includes("HACKED MARKER"));

    // Authoritative state is unchanged.
    const after = await adapter.list();
    assert.deepEqual(after, before);

    // Re-render overwrites the hand-edit.
    await writeTasksMd(tmp);
    const reRendered = readFileSync(target, "utf8");
    assert.ok(!reRendered.includes("HACKED MARKER"), "re-render must overwrite hand-edits");
  });
});
